#ifndef PRODUCT_H
#define PRODUCT_H

#include <iostream>
#include <string>

class Product {
public:
    Product() = default; // default constructor
    Product(const Product&); // copy constructor
    Product(Product&&); // move constructor
    Product& operator=(const Product&) = default; // copy assignment operator
    Product& operator=(Product&&) = default; // move assignment operator

    // destructor is not declared, should be generated by the compiler 

public:
    void set_name(const std::string&);
    std::string name() const;
    void set_availability(bool);
    bool available() const;
    
    // code omitted for brevity

private:  
    std::string name_;
    double price_;
    int rating_;
    bool available_;
};  

std::ostream& operator<<(std::ostream&, const Product&);
std::istream& operator>>(std::istream&, Product&);

#endif // PRODUCT_H
